packages:
  - 'mobile-app'
  - 'app'
  - 'app/**'
  - 'features/**'
  - 'lib/**'
  - 'components/**'
  - 'mobile-app/**'
allowBuilds:
  '@clerk/shared': true
  esbuild: true
  sharp: true
  unrs-resolver: true
